### ISSUE TITLE
TAPi18n.publish / subscribe never ready in Iron Router 1.0.0

### ISSUE THREAD

**Issue by rijk** [TAPevents/tap-i18n-db#8]
Since the update to Meteor 1.0.0, one of my routes that depends on the `@ready()` state doesn't work anymore. This seems to be a problem with TAPi18n, because if I change my publish/subscribe methods back to `Meteor.publish` the problem goes away.

Route:

``` coffeescript
@route '/home',
    path: '/home'
    subscriptions: -> TAPi18n.subscribe 'courses'
    action: -> console.log 'home', @ready() # never true
```

Publication (fake):

``` coffeescript
TAPi18n.publish 'courses', ->
    @ready()
```

This never prints `true` to the console. However, this does:

Route:

``` coffeescript
@route '/home',
    path: '/home'
    subscriptions: -> Meteor.subscribe 'courses'
    action: -> console.log 'home', @ready()
```

Publication:

``` coffeescript
Meteor.publish 'courses', ->
    @ready()
```

**Comment by ChenRoth** [comment]
hey

I've just added i18n-db package and it seems neat
However, I have an issue with Iron router waiting on a TAPi18n.subscribe and it's never ready

I'm using v0.4.0 with iron:router 1.0.7 on Meteor 1.0.3.1

the reproduction is trivial - 

I have a collection declared using TAPi18n.Collection,
a publication declared using TAPi18n.publish
and the subscription is declared within a waitOn array using TAPi18n.subscribe

Also, I'm using the package successfully elsewhere in the project, so it doesn't seem like a "user problem" :)

Any thoughts?
