### ISSUE TITLE
i18nFind() does not work in publication

### ISSUE THREAD

**Issue by Elfoslav** [TAPevents/tap-i18n-db#9]
I define collection Persons:

    Persons = new TAPi18n.Collection("persons");

I have publication on the server:

    TAPi18n.publish("persons", function () {
      return Persons.i18nFind();
    });

And subscription on the client:

    TAPi18n.subscribe('persons', function(err) {
      console.log('subscr persons: ', err);
    });

If I use i18nFind() in publish, I get following error:

![screenshot from 2014-12-10 23 10 56](https://cloud.githubusercontent.com/assets/1983575/5385791/ebfae41c-80c5-11e4-9d87-8e00d07b2b0d.png)

If I use find(), there is no error but translation does not work after changing language.

Tested with Meteor 1.0.1 and 0.9.4

Here is example app: https://github.com/Elfoslav/tap-i18n-example

**Comment by Elfoslav** [comment]
Added project-tap.i18n with supported languages in root of my project and everything is ok.

**Comment by theosp** [comment]
Thanks for the update!

-Daniel

MeteorSpark
http://www.MeteorSpark.com <http://www.meteorspark.com/>
